### ISSUE TITLE
any class name proposed

### ISSUE THREAD

**Issue by flor68** [ucym/Brackets-CSS-Class-Code-hint#3]
I cant make it work, it doesn't propose any class name from my css file.

The css file is linked in the html file and they are in the same folder :/ Any solution ?

**Comment by borkie** [comment]
idem here

**Comment by ucym** [comment]
Please show me a link tag that reads the css.

**Comment by flor68** [comment]
Like that < link rel="stylesheet" type="text/css" href="css.css" >, ty

**Comment by sander76** [comment]
The strange thing is it works in one project folder and not in the other....

**Comment by sander76** [comment]
Removed all my other plugins, but still the problem is there... Inline styles get picked up. But css files are not scanned somehow....

**Comment by ucym** [comment]
What "works in one project folder and not in the other"?

**Comment by sander76** [comment]
I am working on two projects:
Class completion was (somewhat) working in project 1.
Project 2, which I started later was not working.

However, it seems in project 1 it doesn't work anymore either.
Could the sprint34 update have something to do with it?

I tried a css file created by myself with a very simple .menu class  which doesn't work.
An a bootstrap css class doesn't work either.
I move the first file from the css folder to the root folder, which doesn't help either.
Class code completion only seems to work with inline styles...

I am looking at the console for errors but nothing shows....

Thinking ahead.
I am using angularjs. It uses templates which are html files only populated with content (divs etc.) No reference to any css file or anything. Will class completion work on these files too ? (will your plugin scan any css file inside a defined css folder ?)

Sander.

**Comment by ucym** [comment]
Problem might have be resolved.
Would like to ask a review.

0674272bac.

**Comment by sander76** [comment]
It seems to be working. However, cpu is way up and brackets becomes pretty unresponsive. (I have a quick laptop)

Reason could be your plugin starts making suggestions right away without having typed any text, yet resulting in a pretty big list of suggestions ?... Possibly trigger only suggestions after 3 (?) characters have been entered ?

Sander.

**Comment by sander76** [comment]
still no solution ? Memory peaks at 1 gig. Brackets is not really usable this way...

**Comment by sander76** [comment]
A suggestion:
I have -for example- installed bootstrap using bower. These include several css files which have a lot of overlap (the "normal" and minified versions for example.) Could this be a cause for your extensions slowing brackets down ?

**Comment by ucym** [comment]
Continue on #6
