### ISSUE TITLE
Will not work in Brackets Sprint 34

### ISSUE THREAD

**Issue by peterflynn** [ucym/Brackets-CSS-Class-Code-hint#4]
This extension uses the `FileEntry.getMetadata()` API, which has been removed. In the next release of Brackets, the extension will crash or no longer load.

It should be straightforward to switch to the new `File.stat()` API (note that the fields of the result object have changed as well).  You can release this update in advance if you want, since users of Brackets Sprint 33 (the current release) will still be able to install the older version of your extension that is compatible with their build.

See the [migration guide](https://github.com/adobe/brackets/wiki/File-System-API-Migration) and [discussion thread](https://groups.google.com/forum/#!topic/brackets-dev/95PyDKfMO0M) for details.

**Comment by peterflynn** [comment]
Btw: it looks like you're using this API to implement some sort of cache.  I'm working on a new caching API that will hopefully be added to Brackets soon.  You might be able to use it to simplify your code here.  This early draft should give you a sense of what the API will look like: https://github.com/adobe/brackets/compare/master...pflynn;perfilecache-filesys#diff-4d024e2ca42cc9ba938da170c0bb644eR28

**Comment by peterflynn** [comment]
There are also several uses of deprecated APIs in this extension:
- `NativeFileSystem.resolveNativeFileSystemPath`
- `DirectoryEntry.createReader()`

These APIs _should_ continue to work in Brackets Sprint 34, so you do not necessarily need to clean them up at the same time as fixing the breaking changes above.  But the APIs will go away by the end of this year, so you should migrate away from them as soon as you have time (see same [migration guide](https://github.com/adobe/brackets/wiki/File-System-API-Migration) as above).

**Comment by ucym** [comment]
Thanks your information.
Now support on brackets 34 new file system.
